name: Run Game

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-game:
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip

        echo "Searching for requirements.txt files..."
        find . -name "requirements.txt" -type f | while read req; do
          echo "Installing dependencies from: $req"
          pip install -r "$req"
        done

    - name: Run Game Script
      id: run-security-tests
      if: always()
      run: |
        python main.py

    # Commit and Push Changes
    - name: Commit and Push Changes
      run: |
        # configure user
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
        # stage any file changes to be committed
        git add .
    
        # make commit with staged changes
        git commit -m 'game played'
    
        # push the commit back up to source GitHub repository
        git push

    - name: Display Wins
      if: always()
      run: |
        echo "## Game Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat data/wins.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
